<a href="https://colab.research.google.com/github/cntrvsy/colab/blob/main/st20343345_CMP7005_PRAC1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INTRODUCTION

**Let's start by loading in our data from the GitHub Repo**

| No. | File Name                     | No. | File Name                     |
|-----|-------------------------------|-----|-------------------------------|
| 1   | Ahmedabad_data.csv            | 14  | Guwahati_data.csv             |
| 2   | Aizawl_data.csv               | 15  | Hyderabad_data.csv            |
| 3   | Amaravati_data.csv            | 16  | Jaipur_data.csv               |
| 4   | Amritsar_data.csv             | 17  | Jorapokhar_data.csv           |
| 5   | Bengaluru_data.csv            | 18  | Kochi_data.csv                |
| 6   | Bhopal_data.csv               | 19  | Kolkata_data.csv              |
| 7   | Brajrajnagar_data.csv         | 20  | Lucknow_data.csv              |
| 8   | Chandigarh_data.csv           | 21  | Mumbai_data.csv               |
| 9   | Chennai_data.csv              | 22  | Patna_data.csv                |
| 10  | Coimbatore_data.csv           | 23  | Shillong_data.csv             |
| 11  | Delhi_data.csv                | 24  | Talcher_data.csv              |
| 12  | Ernakulam_data.csv            | 25  | Thiruvananthapuram_data.csv   |
| 13  | Gurugram_data.csv             | 26  | Visakhapatnam_data.csv        |

In [20]:
import pandas as pd
import numpy as np

city_names = [
    'Ahmedabad', 'Aizawl', 'Amaravati', 'Amritsar', 'Bengaluru', 'Bhopal',
    'Brajrajnagar', 'Chandigarh', 'Chennai', 'Coimbatore', 'Delhi', 'Ernakulam',
    'Gurugram', 'Guwahati', 'Hyderabad', 'Jaipur', 'Jorapokhar', 'Kochi',
    'Kolkata', 'Lucknow', 'Mumbai', 'Patna', 'Shillong', 'Talcher',
    'Thiruvananthapuram', 'Visakhapatnam'
]

dataframes = {}
for city in city_names:
    url = f'https://raw.githubusercontent.com/cntrvsy/colab/main/{city}_data.csv'
    dataframes[city] = pd.read_csv(url, header=0)

#FUNDERMENTAL DATA UNDERSTANDING

In [2]:
# combine it into one df
combined_df = pd.concat(dataframes.values())
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29531 entries, 0 to 1461
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  object
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: float64(13), object(3)
memory usage: 3.8+ MB

In [3]:
combined_df.head(3)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,01/01/2015,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,02/01/2015,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,03/01/2015,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN

In [5]:
#How many rows and columns are in your merged dataset?
combined_df.shape
print(f'No of Rows: {combined_df.shape[0]}, No of Columns: {combined_df.shape[1]}')

No of Rows: 29531, No of Columns: 16

In [7]:
combined_df.columns

Index(['City', 'Date', 'PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2',
       'O3', 'Benzene', 'Toluene', 'Xylene', 'AQI', 'AQI_Bucket'],
      dtype='object')

In [8]:
combined_df.describe()
# add inference here so what each could tell us

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI
count,24933.000000,18391.000000,25949.000000,25946.000000,25346.000000,19203.000000,27472.000000,25677.000000,25509.000000,23908.000000,21490.000000,11422.000000,24850.000000
mean,67.450578,118.127103,17.574730,28.560659,32.309123,23.483476,2.248598,14.531977,34.491430,3.280840,8.700972,3.070128,166.463581
std,64.661449,90.605110,22.785846,24.474746,31.646011,25.684275,6.962884,18.133775,21.694928,15.811136,19.969164,6.323247,140.696585
min,0.040000,0.010000,0.020000,0.010000,0.000000,0.010000,0.000000,0.010000,0.010000,0.000000,0.000000,0.000000,13.000000
25%,28.820000,56.255000,5.630000,11.750000,12.820000,8.580000,0.510000,5.670000,18.860000,0.120000,0.600000,0.140000,81.000000
50%,48.570000,95.680000,9.890000,21.690000,23.520000,15.850000,0.890000,9.160000,30.840000,1.070000,2.970000,0.980000,118.000000
75%,80.590000,149.745000,19.950000,37.620000,40.127500,30.020000,1.450000,15.220000,45.570000,3.080000,9.150000,3.350000,208.000000
max,949.990000,1000.000000,390.680000,362.210000,467.630000,352.890000,175.810000,193.860000,257.730000,455.030000,454.850000,170.370000,2049.000000

In [9]:
#Which Pollutants are included, and which have the most missing data?
combined_df.isnull().sum()

City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

In [11]:
#How many unique cities are there?
combined_df['City'].nunique()

26

In [10]:
def missing_values_table(combined_df):
    # Total missing values
    mis_val = combined_df.isnull().sum()

    # Percentage of missing values
    mis_val_percent = 100 * mis_val / len(combined_df)

    mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)

    mis_val_table = mis_val_table.rename(columns={0: 'Missing Values', 1: '% of Total Values'})

    # Sort the table by percentage of missing descending
    mis_val_table = mis_val_table.sort_values('% of Total Values', ascending=False)

    return mis_val_table

missing_values = missing_values_table(combined_df)
display(missing_values.style.background_gradient(cmap='Reds'))

#DATA CLEANING

In [29]:
#Convert Order Date to a proper datetime format.
combined_df['Date'] = pd.to_datetime(combined_df['Date'], format="mixed", errors="coerce")

# Xylene
xylene_median = combined_df['Xylene'].median()
combined_df['Xylene'] = combined_df['Xylene'].fillna(xylene_median)
print(f"Missing values in 'Xylene' column after median imputation: {combined_df['Xylene'].isnull().sum()}")

#PM10
pm10_median = combined_df['PM10'].median()
combined_df['PM10'] = combined_df['PM10'].fillna(pm10_median)
print(f"Missing values in 'PM10' column after median imputation: {combined_df['PM10'].isnull().sum()}")

#NH3
nh3_median = combined_df['NH3'].median()
combined_df['NH3'] = combined_df['NH3'].fillna(nh3_median)
print(f"Missing values in 'NH3' column after median imputation: {combined_df['NH3'].isnull().sum()}")

Missing values in 'Xylene' column after median imputation: 0
Missing values in 'PM10' column after median imputation: 0
Missing values in 'NH3' column after median imputation: 0

In [31]:
combined_df.isnull().sum()

City             0
Date             0
PM2.5         4598
PM10             0
NO            3582
NO2           3585
NOx           4185
NH3              0
CO            2059
SO2           3854
O3            4022
Benzene       5623
Toluene       8041
Xylene           0
AQI           4681
AQI_Bucket    4681
dtype: int64

In [26]:
import numpy as np
import pandas as pd

def aqi_to_bucket(aqi):
    if pd.isna(aqi):
        return np.nan
    aqi = float(aqi)
    if aqi <= 50:
        return "good"
    if aqi <= 100:
        return "satisfactory"
    if aqi <= 200:
        return "moderate"
    if aqi <= 300:
        return "poor"
    if aqi <= 400:
        return "very poor"
    return "severe"

In [27]:
combined_df['AQI_Bucket'] = combined_df['AQI'].apply(aqi_to_bucket)

# Display the first few rows to show the updated AQI_Bucket
display(combined_df[['AQI', 'AQI_Bucket']].head())

   AQI AQI_Bucket
0  NaN        NaN
1  NaN        NaN
2  NaN        NaN
3  NaN        NaN
4  NaN        NaN

#Inference - DATA CLEANING
 - For most of the pollutant columns (PM2.5, NO, NO2, NOx, NH3, CO, SO2, O3, Benzene, Toluene, and AQI), the median is likely the most appropriate choice as Pollutant levels are rarely perfectly normally distributed and often have higher frequencies at lower concentrations with occasional high peaks.
 -Mean wouldnt work as it is sensitive to extreme values in the dataset.

In [30]:
missing_values_after_aqi_bucket = missing_values_table(combined_df)
display(missing_values_after_aqi_bucket.style.background_gradient(cmap='Reds'))

Missing values in 'Xylene' column after median imputation: 0

### Handling Missing Values in PM10

Following the strategy used for Xylene, we will now impute the missing values in the 'PM10' column. The median value will be used for imputation to maintain data integrity and robustness against potential outliers in pollutant measurements.

In [25]:
pm10_median = combined_df['PM10'].median()
combined_df['PM10'] = combined_df['PM10'].fillna(pm10_median)
print(f"Missing values in 'PM10' column after median imputation: {combined_df['PM10'].isnull().sum()}")

Missing values in 'PM10' column after median imputation: 0